apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s_deployment.yaml
patchesStrategicMerge:
  - contrast-java-agent.yaml
secretGenerator:
  - name: contrast-security
    files:
    - contrast_security.yaml
