apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
patchesStrategicMerge:
  - contrast-java-agent.yaml
secretGenerator:
  - name: contrast-security
    files:
    - contrast_security.yaml
